### ISSUE TITLE
Add OpenTelemetry Metrics Export for Development Workflow

### ISSUE THREAD

**Issue by skorfmann** [boldsoftware/sketch#176]
## Summary

Enable developers to export Sketch usage metrics to their local OpenTelemetry collector for personal usage tracking and analysis.

## Use Case

As a developer using Sketch daily, I want to:
- Track my LLM token usage and costs over time
- Analyze which tools I use most frequently
- Monitor usage patterns to optimize my prompts
- Build personal dashboards in Grafana/Prometheus

### Configuration

Add optional OpenTelemetry configuration via config file or environment variables:

```yaml
# .sketch/config.yaml
otel:
  enabled: false  # opt-in, default false
  endpoint: "localhost:4317"  # OTLP gRPC endpoint
  protocol: "grpc"  # or "http"
  headers: {}  # optional headers for auth
  interval: "60s"  # export interval
```

Or via environment variables:
```bash
SKETCH_OTEL_ENABLED=true
SKETCH_OTEL_ENDPOINT=localhost:4317
```

### Metrics to Export

Export the existing usage data as OpenTelemetry metrics with proper granularity:

- `sketch.llm.tokens.total` (counter) - labels: `type={input|output}`, `cache={hit|miss|creation}`
- `sketch.llm.requests.total` (counter) - labels: `model`, `status={success|error}`
- `sketch.llm.request.duration` (histogram) - labels: `model`
- `sketch.llm.cost.total` (counter) - labels: `model`, `currency=usd`
- `sketch.tools.calls.total` (counter) - labels: `tool`, `status={success|error}`
- `sketch.tools.duration` (histogram) - labels: `tool`

### Implementation Details

- Use OpenTelemetry Go SDK
- Export existing usage data only
- No new collection or storage
- Disabled by default
- No performance impact when disabled
- Graceful degradation if endpoint unavailable

## Example Setup

```bash
# Start local OTEL collector with Prometheus exporter
docker run -p 4317:4317 -p 9090:9090 otel/opentelemetry-collector

# Configure Sketch
cat > ~/.sketch/config.yaml << EOF
otel:
  enabled: true
  endpoint: "localhost:4317"
  interval: "30s"
EOF

# Run Sketch
sketch

# View metrics in Prometheus at http://localhost:9090
# Query examples:
# - rate(sketch_llm_tokens_total[5m])
# - sum(sketch_llm_cost_total) by (model)
# - histogram_quantile(0.95, sketch_tools_duration_bucket)
```

This would help developers understand and optimize their Sketch usage without adding complexity to the tool itself.
